spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.67.154.97:3306/wcy
    username: root
    password: wcy19930921
  redis:
    host: 114.67.154.97
    port: 6379
    password: wcy19930921

mybatis:
  typeAliasesPackage: me.wcy.learnspring.entity
  mapperLocations: classpath:mapper/*.xml