spring:
  resources:
    static-locations: file:./learnspring/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wcy
    username: root
    password: wcy19930921
  redis:
    host: localhost
    port: 6379
    password: wcy19930921

mybatis:
  typeAliasesPackage: me.wcy.learnspring.entity
  mapperLocations: classpath:mapper/*.xml

keytool:
  javaPath: /usr/lib/jvm/java-1.8.0/bin/
  keyPath: /home/keytool/
