server:
  port: 8101
spring:
  application:
    name: xiaocao
  dubbo:
    application:
      name: xiaocao-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
    scan: me.wcy.spring.xiaocao.remote

zipkin:
  enable: true
  baseUrl: http://localhost:9411
  serviceName: xiaocao
